// src/application/services/memory.service.ts

import type { IStoragePort } from '@core/ports/output/storage.port';
import type { IVectorPort } from '@core/ports/output/vector.port';
import type { IEventBus } from '@core/ports/notification/event-bus.port';
import type { MemoryEntry, Message, Session } from '@core/domain/types';

/**
 * MemoryService handles session memory, long-term memory, and auto-cleanup.
 * Session memory: current conversation (TIER 2)
 * Long-term memory: cross-session persistent knowledge (TIER 1)
 * Auto-cleanup: progressive summarization when context pressure detected
 */
export class MemoryService {
  constructor(
    private readonly storage: IStoragePort,
    private readonly vector: IVectorPort,
    private readonly eventBus: IEventBus,
  ) {}

  async saveSessionMemory(sessionId: string, messages: Message[]): Promise<void> {
    for (const msg of messages) {
      await this.storage.saveMemory({
        id: msg.id,
        content: msg.content,
        category: `session:${sessionId}`,
        tags: [msg.role, msg.model],
        createdAt: msg.createdAt,
        updatedAt: new Date(),
      });
    }

    this.eventBus.emit({
      type: 'memory.session.saved',
      payload: { sessionId, messageCount: messages.length },
      timestamp: new Date(),
    });
  }

  async archiveSession(session: Session): Promise<string> {
    const summary = this.generateSummary(session.messages);

    await this.storage.saveMemory({
      id: crypto.randomUUID(),
      content: summary,
      category: 'session-archives',
      tags: [session.type, session.id],
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    await this.vector.upsert('long-term-memory', [{
      id: session.id,
      values: [], // embedding generated by infrastructure adapter
      payload: { summary, sessionId: session.id, type: session.type },
    }]);

    this.eventBus.emit({
      type: 'memory.session.archived',
      payload: { sessionId: session.id, summaryLength: summary.length },
      timestamp: new Date(),
    });

    return summary;
  }

  async recallMemory(query: string, limit: number = 5): Promise<MemoryEntry[]> {
    return this.storage.recallMemory(query, limit);
  }

  async autoCleanup(sessionId: string, messages: Message[], maxMessages: number): Promise<Message[]> {
    if (messages.length <= maxMessages) return messages;

    const toArchive = messages.slice(0, messages.length - maxMessages);
    const toKeep = messages.slice(-maxMessages);

    // Archive older messages
    await this.saveSessionMemory(sessionId, toArchive);

    this.eventBus.emit({
      type: 'memory.auto.cleanup',
      payload: { sessionId, archived: toArchive.length, kept: toKeep.length },
      timestamp: new Date(),
    });

    return toKeep;
  }

  private generateSummary(messages: Message[]): string {
    // Progressive summarization: extract key points from conversation
    const keyPoints: string[] = [];
    const userMessages = messages.filter(m => m.role === 'user');
    const assistantMessages = messages.filter(m => m.role === 'assistant');

    keyPoints.push(`Session had ${messages.length} messages (${userMessages.length} user, ${assistantMessages.length} assistant).`);

    // Extract first and last topics
    if (userMessages.length > 0) {
      const first = userMessages[0]!;
      const last = userMessages[userMessages.length - 1]!;
      keyPoints.push(`Started with: "${first.content.substring(0, 150)}..."`);
      keyPoints.push(`Ended with: "${last.content.substring(0, 150)}..."`);
    }

    // Key decisions from assistant responses
    for (const msg of assistantMessages.slice(0, 3)) {
      if (msg.sources && msg.sources.length > 0) {
        keyPoints.push(`Referenced: ${msg.sources.map(s => s.title).join(', ')}`);
      }
    }

    return keyPoints.join('\n');
  }
}
